#!/bin/bash

echo "Installing category basic tools"

pacman -Syyu

pacman -S bc rsync mlocate bash-completion pkgstats arch-wiki-lite
pacman -S zip unzip unrar p7zip lzop cpio

pacman -S avahi nss-mdns
system_ctl enable avahi-daemon

pacman -S alsa-utils alsa-plugins
pacman -S pulseaudio pulseaudio-alsa

pacman -S ntfs-3g dosfstools exfat-utils f2fs-tools fuse fuse-exfat autofs mtpfs
